networks:
  dokploy-network:
    external: true

services:
  vane:
    image: itzcrazykns1337/vane:latest
    build:
      context: .
    restart: unless-stopped
    ports:
      - "3010:3000"
    networks:
      - dokploy-network
    volumes:
      - ../files/data:/home/vane/data
      - ../files/uploads:/home/vane/uploads